/*
-- Query: SELECT * FROM temperance_multichoice
LIMIT 0, 1000

-- Date: 2026-01-13 21:38
*/
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('He that is slow to anger is better than the mighty; and he that ruleth his spirit than he that taketh a city.','Proverbs 16:32','Easy','KJV','Temperance','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('For if ye live after the flesh, ye shall die: but if ye through the Spirit do mortify the deeds of the body, ye shall live.','Romans 8:13','Easy','KJV','Temperance','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('He that hath no rule over his own spirit is like a city that is broken down, and without walls.','Proverbs 25:28','Easy','KJV','Temperance','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('For to be carnally minded is death; but to be spiritually minded is life and peace.','Romans 8:6','Easy','KJV','Temperance','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('But as he which hath called you is holy, so be ye holy in all manner of conversation.','1 Peter 1:15','Easy','KJV','Temperance','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.','2 Timothy 1:7','Easy','KJV','Temperance','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Mortify therefore your members which are upon the earth; fornication, uncleanness, inordinate affection, evil concupiscence, and covetousness, which is idolatry:','Colossians 3:5','Intermediate','KJV','Temperance','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('It is good neither to eat flesh, nor to drink wine, nor any thing whereby thy brother stumbleth, or is offended, or is made weak.','Romans 14:21','Difficult','KJV','Temperance','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Meekness, temperance: against such there is no law.','Galatians 5:23','Easy','KJV','Temperance','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('And every man that striveth for the mastery is temperate in all things. Now they do it to obtain a corruptible crown; but we an incorruptible. I therefore so run, not as uncertainly; so fight I, not as one that beateth the air: But I keep under my body, and bring it into subjection: lest that by any means, when I have preached to others, I myself should be a castaway.','1 Corinthians 9:25-27','Difficult','KJV','Temperance','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('When thou sittest to eat with a ruler, consider diligently what is before thee: And put a knife to thy throat, if thou be a man given to appetite. Be not desirous of his dainties: for they are deceitful meat.','Proverbs 23:1-3','Difficult','KJV','Temperance','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('This I say then, Walk in the Spirit, and ye shall not fulfil the lust of the flesh.','Galatians 5:16','Easy','KJV','Temperance','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('And beside this, giving all diligence, add to your faith virtue; and to virtue knowledge; And to knowledge temperance; and to temperance patience; and to patience godliness;','2 Peter 1:5-6','Difficult','KJV','Temperance','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Teaching us that, denying unGodliness and worldly lusts, we should live soberly, righteously, and godly, in this present world.','Titus 2:12','Intermediate','KJV','Temperance','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('But put ye on the Lord Jesus Christ, and make not provision for the flesh, to fulfil the lusts thereof.','Romans 13:14','Intermediate','KJV','Temperance','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Let your moderation be known unto all men. The Lord is at hand.','Philippians 4:5','Intermediate','KJV','Temperance','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Hast thou found honey? eat so much as is sufficient for thee, lest thou be filled therewith, and vomit it.','Proverbs 25:16','Difficult','KJV','Temperance','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Be not hasty in thy spirit to be angry: for anger resteth in the bosom of fools.','Ecclesiastes 7:9','Easy','KJV','Temperance','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('That the aged men be sober, grave, temperate, sound in faith, in charity, in patience.','Titus 2:2','Intermediate','KJV','Temperance','');
