/*
-- Query: SELECT * FROM love_multichoice
LIMIT 0, 1000

-- Date: 2026-01-13 20:53
*/
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('For God so loved the world that he gave his only begotten son, that whosoever believes in him shall not perish, but have everlasting life.','John 3:16','Easy','KJV','Love','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Greater love hath no man than this, that a man lay down his life for his friends.','John 15:13','Easy','KJV','Love','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Owe no man any thing, but to love one another: for he that loveth another hath fulfilled the law.','Romans 13:8','Easy','KJV','Love','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up, Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil; Rejoiceth not in iniquity, but rejoiceth in the truth; Beareth all things, believeth all things, hopeth all things, endureth all things. Charity never faileth.','1 Corinthians 13:4-8','Difficult','KJV','Love','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Hatred stirreth up strifes: but love covereth all sins.','Proverbs 10:12','Easy','KJV','Love','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('And above all things have fervent charity among yourselves: for charity shall cover the multitude of sins.','1 Peter 4:8','Intermediate','KJV','Love','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('And above all these things put on charity, which is the bond of perfectness.','Colossian 3:14','Easy','KJV','Love','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another.','John 13:34','Intermediate','KJV','Love','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('A friend loveth at all times, and a brother is born for adversity.','Proverbs 17:17','Easy','KJV','Love','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Let love be without dissimulation. Abhor that which is evil; cleave to that which is good.','Romans 12:9','Intermediate','KJV','Love','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Thou shalt not avenge, nor bear any grudge against the children of thy people, but thou shalt love thy neighbour as thyself: I am the Lord.','Leviticus 19:18','Easy','KJV','Love','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('And though I have the gift of prophecy, and understand all mysteries, and all knowledge; and though I have all faith, so that I could remove mountains, and have not charity, I am nothing.','1 Corinthians 13:2','Intermediate','KJV','Love','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you;','Matthew 5:44','Easy','KJV','Love','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('There is no fear in love; but perfect love casteth out fear: because fear hath torment. He that feareth is not made perfect in love.','1 John 4:18','Easy','KJV','Love','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind. This is the first and great commandment. And the second is like unto it, Thou shalt love thy neighbour as thyself. On these two commandments hang all the law and the prophets.','Matthew 22:37-40','Difficult','KJV','Love','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('And now abideth faith, hope, charity, these three; but the greatest of these is charity.','1 Corinthians 13:13','Easy','KJV','Love','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Set me as a seal upon thine heart, as a seal upon thine arm: for love is strong as death; jealousy is cruel as the grave: the coals thereof are coals of fire, which hath a most vehement flame.','Song of Solomon 8:6','Intermediate','KJV','Love','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('And we have known and believed the love that God hath to us. God is love; and he that dwelleth in love dwelleth in God, and God in him.','1 John 4:16','Easy','KJV','Love','');
INSERT INTO `` (`QUESTIONS`,`ANSWER`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('No man hath seen God at any time. If we love one another, God dwelleth in us, and his love is perfected in us.','1 John 4:12','Easy','KJV','Love','');
