/*
-- Query: SELECT * FROM longsuffering_scripture
LIMIT 0, 1000

-- Date: 2026-01-13 20:53
*/
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Hebrews 12:1','Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us.','Easy','KJV','Longsuffering','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('2 Peter 3:9','The Lord is not slack concerning his promise, as some men count slackness; but is longsuffering to us-ward, not willing that any should perish, but that all should come to repentance.','Intermediate','KJV','Longsuffering','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Romans 12:12','Rejoicing in hope; patient in tribulation; continuing instant in prayer.','Easy','KJV','Longsuffering','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Psalm 37:7-8','Rest in the Lord, and wait patiently for him: fret not thyself because of him who prospereth in his way, because of the man who bringeth wicked devices to pass. Cease from anger, and forsake wrath: fret not thyself in any wise to do evil.','Intermediate','KJV','Longsuffering','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Proverbs 15:18','A wrathful man stirreth up strife: but he that is slow to anger appeaseth strife.','Easy','KJV','Longsuffering','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('1 Corinthians 13:4','Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up.','Easy','KJV','Longsuffering','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Genesis 29:20A','And Jacob served seven years for Rachel; and they seemed unto him but a few days, for the love he had to her.','Easy','KJV','Longsuffering','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Habakkuk 2:3','For the vision is yet for an appointed time, but at the end it shall speak, and not lie: though it tarry, wait for it; because it will surely come, it will not tarry.','Intermediate','KJV','Longsuffering','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Psalm 27:14','Wait on the Lord: be of good courage, and he shall strengthen thine heart: wait, I say, on the Lord.','Intermediate','KJV','Longsuffering','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Galatians 6:9','And let us not be weary in well doing: for in due season we shall reap, if we faint not.','Intermediate','KJV','Longsuffering','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('James 5:7-8','Be patient therefore, brethren, unto the coming of the Lord. Behold, the husbandman waiteth for the precious fruit of the earth, and hath long patience for it, until he receive the early and latter rain. Be ye also patient; stablish your hearts: for the coming of the Lord draweth nigh.','Difficult','KJV','Longsuffering','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Numbers 14:18','The Lord is longsuffering, and of great mercy, forgiving iniquity and transgression, and by no means clearing the guilty, visiting the iniquity of the fathers upon the children unto the third and fourth generation.','Difficult','KJV','Longsuffering','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Psalm 103:8','The Lord is merciful and gracious, slow to anger, and plenteous in mercy.','Easy','KJV','Longsuffering','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Romans 9:22-23','What if God, willing to shew his wrath, and to make his power known, endured with much longsuffering the vessels of wrath fitted to destruction: And that he might make known the riches of his glory on the vessels of mercy, which he had afore prepared unto glory.','Difficult','KJV','Longsuffering','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('1 Timothy 1:16','Howbeit for this cause I obtained mercy, that in me first Jesus Christ might shew forth all longsuffering, for a pattern to them which should hereafter believe on him to life everlasting.','Difficult','KJV','Longsuffering','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Revelation 6:10-11','And they cried with a loud voice, saying, How long, O Lord, holy and true, dost thou not judge and avenge our blood on them that dwell on the earth? And white robes were given unto every one of them; and it was said unto them, that they should rest yet for a little season, until their fellowservants also and their brethren, that should be killed as they were, should be fulfilled.','Difficult','KJV','Longsuffering','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Ecclesiastes 7:8','Better is the end of a thing than the beginning thereof: and the patient in spirit is better than the proud in spirit.','Easy','KJV','Longsuffering','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Hebrews 10:36','For ye have need of patience, that, after ye have done the will of God, ye might receive the promise.','Easy','KJV','Longsuffering','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Exodus 34:6','And the Lord passed by before him, and proclaimed, The Lord, The Lord God, merciful and gracious, longsuffering, and abundant in goodness and truth.','Intermediate','KJV','Longsuffering','');
