/*
-- Query: SELECT * FROM joy_scripture
LIMIT 0, 1000

-- Date: 2026-01-13 20:54
*/
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('James 1:2-3','My brethren, count it all joy when ye fall into divers temptations; Knowing this, that the trying of your faith worketh patience.','Easy','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('John 16:24','Hitherto have ye asked nothing in my name: ask, and ye shall receive, that your joy may be full.','Easy','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Nehemiah 8 :10','Then he said unto them, Go your way, eat the fat, and drink the sweet, and send portions unto them for whom nothing is prepared: for this day is holy unto our Lord: neither be ye sorry; for the joy of the Lord is your strength.','Intermediate','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Isaiah 35:10','And the ransomed of the Lord shall return, and come to Zion with songs and everlasting joy upon their heads: they shall obtain joy and gladness, and sorrow and sighing shall flee away.','Intermediate','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Psalm 30:5','For his anger endureth but a moment; in his favour is life: weeping may endure for a night, but joy cometh in the morning.','Easy','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Philippians 4:4','Rejoice in the lord alway; and again, I say rejoice.','Easy','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Romans 14:17','For the kingdom of God is not meat and drink; but righteousness, and peace, and joy in the Holy Ghost.','Easy','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('John 16:22','And ye now therefore have sorrow: but I will see you again, and your heart shall rejoice, and your joy no man taketh from you.','Intermediate','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Romans 5:3-5','And not only so, but we glory in tribulations also: knowing that tribulation worketh patience; And patience, experience; and experience, hope: And hope maketh not ashamed; because the love of God is shed abroad in our hearts by the Holy Ghost which is given unto us.','Intermediate','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Psalm 16:11','Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are pleasures for evermore.','Intermediate','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Luke 15:6-7','And when he cometh home, he calleth together his friends and neighbours, saying unto them, Rejoice with me; for I have found my sheep which was lost. I say unto you, that likewise joy shall be in heaven over one sinner that repenteth, more than over ninety and nine just persons, which need no repentance.','Difficult','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Romans 12:12','Rejoicing in hope; patient in tribulation; continuing instant in prayer;','Easy','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('John 15:11','These things have I spoken unto you, that my joy might remain in you, and that your joy might be full.','Easy','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Psalm 118:24','This is the day which the Lord hath made; we will rejoice and be glad in it.','Easy','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Proverbs 10:28','The hope of the righteous shall be gladness: but the expectation of the wicked shall perish.','Intermediate','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Psalm 71:23','My lips shall greatly rejoice when I sing unto thee; and my soul, which thou hast redeemed.','Easy','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Zephaniah 3:17','The Lord thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing.','Intermediate','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Hebrews 12:2','Looking unto Jesus the author and finisher of our faith; who for the joy that was set before him endured the cross, despising the shame, and is set down at the right hand of the throne of God.','Intermediate','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('1 Thessalonians 5:16-18','Rejoice evermore. Pray without ceasing. In every thing give thanks: for this is the will of God in Christ Jesus concerning you.','Easy','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('1 Chronicles 16:27','Glory and honour are in his presence; strength and gladness are in his place.','Easy','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Psalm 32:11','Be glad in the Lord, and rejoice, ye righteous: and shout for joy, all ye that are upright in heart.','Easy','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Isaiah 55:12','For ye shall go out with joy, and be led forth with peace: the mountains and the hills shall break forth before you into singing, and all the trees of the field shall clap their hands.','Intermediate','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Psalm 126:5','They that sow in tears shall reap in joy.','Easy','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Psalm 100:1','Make a joyful noise unto the Lord, all ye lands.','Easy','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Jeremiah 15:16','Thy words were found, and I did eat them; and thy word was unto me the joy and rejoicing of mine heart: for I am called by thy name, O Lord God of hosts.','Intermediate','KJV','Joy','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Proverbs 12:20','Deceit is in the heart of them that imagine evil: but to the counsellors of peace is joy.','Intermediate','KJV','Joy','');
