/*
-- Query: SELECT * FROM love_scripture
LIMIT 0, 1000

-- Date: 2026-01-13 20:53
*/
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('John 3:16','For God so loved the world that he gave his only begotten son, that whosoever believes in him shall not perish, but have everlasting life.','Easy','KJV','Love','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('John 15:13','Greater love hath no man than this, that a man lay down his life for his friends.','Easy','KJV','Love','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Romans 13:8','Owe no man any thing, but to love one another: for he that loveth another hath fulfilled the law.','Easy','KJV','Love','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('1 Corinthians 13:4-8','Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up, Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil; Rejoiceth not in iniquity, but rejoiceth in the truth; Beareth all things, believeth all things, hopeth all things, endureth all things. Charity never faileth.','Difficult','KJV','Love','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Proverbs 10:12','Hatred stirreth up strifes: but love covereth all sins.','Easy','KJV','Love','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('1 Peter 4:8','And above all things have fervent charity among yourselves: for charity shall cover the multitude of sins.','Intermediate','KJV','Love','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Colossian 3:14','And above all these things put on charity, which is the bond of perfectness.','Easy','KJV','Love','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('John 13:34','A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another.','Intermediate','KJV','Love','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Proverbs 17:17','A friend loveth at all times, and a brother is born for adversity.','Easy','KJV','Love','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Romans 12:9','Let love be without dissimulation. Abhor that which is evil; cleave to that which is good.','Intermediate','KJV','Love','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Leviticus 19:18','Thou shalt not avenge, nor bear any grudge against the children of thy people, but thou shalt love thy neighbour as thyself: I am the Lord.','Easy','KJV','Love','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('1 Corinthians 13:2','And though I have the gift of prophecy, and understand all mysteries, and all knowledge; and though I have all faith, so that I could remove mountains, and have not charity, I am nothing.','Intermediate','KJV','Love','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Matthew 5:44','But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you;','Easy','KJV','Love','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('1 John 4:18','There is no fear in love; but perfect love casteth out fear: because fear hath torment. He that feareth is not made perfect in love.','Easy','KJV','Love','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Matthew 22:37-40','Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind. This is the first and great commandment. And the second is like unto it, Thou shalt love thy neighbour as thyself. On these two commandments hang all the law and the prophets.','Difficult','KJV','Love','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('1 Corinthians 13:13','And now abideth faith, hope, charity, these three; but the greatest of these is charity.','Easy','KJV','Love','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('Song of Solomon 8:6','Set me as a seal upon thine heart, as a seal upon thine arm: for love is strong as death; jealousy is cruel as the grave: the coals thereof are coals of fire, which hath a most vehement flame.','Intermediate','KJV','Love','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('1 John 4:16','And we have known and believed the love that God hath to us. God is love; and he that dwelleth in love dwelleth in God, and God in him.','Easy','KJV','Love','');
INSERT INTO `` (`VERSE`,`SCRIPTURE`,`LOD`,`TRANSLATION`,`FRUIT`,`CATEGORY`) VALUES ('1 John 4:12','No man hath seen God at any time. If we love one another, God dwelleth in us, and his love is perfected in us.','Easy','KJV','Love','');
