/*
-- Query: SELECT * FROM user
LIMIT 0, 1000

-- Date: 2026-01-13 20:37
*/
INSERT INTO `` (`id`,`email`,`first_name`,`last_name`,`password`,`username`,`enabled`,`account_expiry_date`,`account_non_expired`,`account_non_locked`,`create_date`,`credentials_expiry_date`,`credentials_non_expired`,`is_two_factor_enabled`,`sign_up_method`,`two_factor_secret`,`updated_date`,`role_id`) VALUES (2,'jwhite@gmail.com','Joshua','White','$2a$10$0b8kfYtfUWncFZ.opkXDquSEF8MVLqKDXoeo/iFQEtL2aRtiHPESS','admin_joshua',1,NULL,'0','0',NULL,NULL,'0','0',NULL,NULL,'2025-12-09 04:36:12.667004',NULL);
INSERT INTO `` (`id`,`email`,`first_name`,`last_name`,`password`,`username`,`enabled`,`account_expiry_date`,`account_non_expired`,`account_non_locked`,`create_date`,`credentials_expiry_date`,`credentials_non_expired`,`is_two_factor_enabled`,`sign_up_method`,`two_factor_secret`,`updated_date`,`role_id`) VALUES (3,'jawhite@gmail.com','Justin','White','$2a$10$B2K4Jl3ZmEhiaDTyAgjv4OvKbXY/yK4/cmysJ4fKI5sr4k/QeoGk.','admin_jaw',1,NULL,'0','0',NULL,NULL,'0','0',NULL,NULL,'2025-12-09 04:36:12.735742',NULL);
INSERT INTO `` (`id`,`email`,`first_name`,`last_name`,`password`,`username`,`enabled`,`account_expiry_date`,`account_non_expired`,`account_non_locked`,`create_date`,`credentials_expiry_date`,`credentials_non_expired`,`is_two_factor_enabled`,`sign_up_method`,`two_factor_secret`,`updated_date`,`role_id`) VALUES (4,'lmwhite@gmail.com','Lauren','Thomas','$2a$10$grdaMUGu4qAUIoGB4ZlMSOqhbb91QXEj2bFttj1aEMXy1vJKhiD.q','admin_l',1,NULL,'0','0',NULL,NULL,'0','0',NULL,NULL,'2025-12-09 04:36:12.792482',NULL);
INSERT INTO `` (`id`,`email`,`first_name`,`last_name`,`password`,`username`,`enabled`,`account_expiry_date`,`account_non_expired`,`account_non_locked`,`create_date`,`credentials_expiry_date`,`credentials_non_expired`,`is_two_factor_enabled`,`sign_up_method`,`two_factor_secret`,`updated_date`,`role_id`) VALUES (5,'cthomas@gmail.com','Charles','Thomas','$2a$10$/XU4XZdVHvQN.QZ6ixvnCe9SIcqYIF9zwBQqwDE6ug7Y3dsYDTK0G','teflonChuck',1,NULL,'0','0',NULL,NULL,'0','0',NULL,NULL,'2025-12-09 04:36:12.850031',NULL);
INSERT INTO `` (`id`,`email`,`first_name`,`last_name`,`password`,`username`,`enabled`,`account_expiry_date`,`account_non_expired`,`account_non_locked`,`create_date`,`credentials_expiry_date`,`credentials_non_expired`,`is_two_factor_enabled`,`sign_up_method`,`two_factor_secret`,`updated_date`,`role_id`) VALUES (6,'stthomas@gmail.com','Sinai','Thomas','$2a$10$V0dKVX/JtWZrGW.X9xxw0ehP7OWkChHqScXbeGcD2.LS4zbzea5X2','saint.thomas',1,NULL,'0','0',NULL,NULL,'0','0',NULL,NULL,'2025-12-09 04:36:12.907282',NULL);
INSERT INTO `` (`id`,`email`,`first_name`,`last_name`,`password`,`username`,`enabled`,`account_expiry_date`,`account_non_expired`,`account_non_locked`,`create_date`,`credentials_expiry_date`,`credentials_non_expired`,`is_two_factor_enabled`,`sign_up_method`,`two_factor_secret`,`updated_date`,`role_id`) VALUES (7,'lwhite@gmail.com','Lisa','White','$2a$10$V.ESg60X7othlGblaunZvONMISWlsQN9Lw0zS./qzo09cAJrm06Na','admin_lisa',1,NULL,'0','0',NULL,NULL,'0','0',NULL,NULL,'2025-12-09 04:36:12.964955',NULL);
INSERT INTO `` (`id`,`email`,`first_name`,`last_name`,`password`,`username`,`enabled`,`account_expiry_date`,`account_non_expired`,`account_non_locked`,`create_date`,`credentials_expiry_date`,`credentials_non_expired`,`is_two_factor_enabled`,`sign_up_method`,`two_factor_secret`,`updated_date`,`role_id`) VALUES (8,'twhite@gmail.com','Anthony','White','$2a$10$oNumm5DzD8KyzXCdvK4xweiFynQMSwFr06tWdI4xW2uV48lrBoCz6','tbird3207',1,NULL,'0','0',NULL,NULL,'0','0',NULL,NULL,'2025-12-09 04:36:13.022025',NULL);
INSERT INTO `` (`id`,`email`,`first_name`,`last_name`,`password`,`username`,`enabled`,`account_expiry_date`,`account_non_expired`,`account_non_locked`,`create_date`,`credentials_expiry_date`,`credentials_non_expired`,`is_two_factor_enabled`,`sign_up_method`,`two_factor_secret`,`updated_date`,`role_id`) VALUES (9,'awhite@gmail.com','Alysia','White','$2a$10$psTwsRBmpz6NU/UWPhnQ0O/XzYpPRZlC69XehW3j2imidtvTuFAvC','bigLeesh',1,NULL,'0','0',NULL,NULL,'0','0',NULL,NULL,'2025-12-09 04:36:13.151305',NULL);
INSERT INTO `` (`id`,`email`,`first_name`,`last_name`,`password`,`username`,`enabled`,`account_expiry_date`,`account_non_expired`,`account_non_locked`,`create_date`,`credentials_expiry_date`,`credentials_non_expired`,`is_two_factor_enabled`,`sign_up_method`,`two_factor_secret`,`updated_date`,`role_id`) VALUES (10,'cwhite@gmail.com','Cameron','White','$2a$10$TEmcq00bysPFg0qWCzdz0elDuzAG6wkAWVLNdEqZFKRELuHp7o4N2','cdub97',1,NULL,'0','0',NULL,NULL,'0','0',NULL,NULL,'2025-12-09 04:36:13.224289',NULL);
INSERT INTO `` (`id`,`email`,`first_name`,`last_name`,`password`,`username`,`enabled`,`account_expiry_date`,`account_non_expired`,`account_non_locked`,`create_date`,`credentials_expiry_date`,`credentials_non_expired`,`is_two_factor_enabled`,`sign_up_method`,`two_factor_secret`,`updated_date`,`role_id`) VALUES (11,'franklinmilo@gmail.com','Frankie','White','$2a$10$Kgn40uw4rqx51dtHzTUNaeW0zxPnviQUsTi9yStg8pkyJFMz0Rl0u','lilMilo',1,NULL,'0','0',NULL,NULL,'0','0',NULL,NULL,'2025-12-09 04:36:13.282118',NULL);
INSERT INTO `` (`id`,`email`,`first_name`,`last_name`,`password`,`username`,`enabled`,`account_expiry_date`,`account_non_expired`,`account_non_locked`,`create_date`,`credentials_expiry_date`,`credentials_non_expired`,`is_two_factor_enabled`,`sign_up_method`,`two_factor_secret`,`updated_date`,`role_id`) VALUES (12,'deuceydeu@gmail.com','Deuce','Thomas','$2a$10$2gqEUvhs.nfKwCCB1MNxDuX5Az5lbo5zu187ohQwxVbXSG/Juk6sK','deuceDeuce',1,NULL,'0','0',NULL,NULL,'0','0',NULL,NULL,'2025-12-09 04:36:13.339308',NULL);
INSERT INTO `` (`id`,`email`,`first_name`,`last_name`,`password`,`username`,`enabled`,`account_expiry_date`,`account_non_expired`,`account_non_locked`,`create_date`,`credentials_expiry_date`,`credentials_non_expired`,`is_two_factor_enabled`,`sign_up_method`,`two_factor_secret`,`updated_date`,`role_id`) VALUES (13,'eddieK@gmail.com','Eddie','Kane','$2a$10$3FrFiUlJGwppaWv0hcZWfeYHnx69avNlwOdayDbsSca37e2alq1Bu','eddieKane',1,NULL,'0','0',NULL,NULL,'0','0',NULL,NULL,'2025-12-09 04:36:13.398170',NULL);
INSERT INTO `` (`id`,`email`,`first_name`,`last_name`,`password`,`username`,`enabled`,`account_expiry_date`,`account_non_expired`,`account_non_locked`,`create_date`,`credentials_expiry_date`,`credentials_non_expired`,`is_two_factor_enabled`,`sign_up_method`,`two_factor_secret`,`updated_date`,`role_id`) VALUES (29,'kabg@gmail.com','Kara','Gruenewald','$2a$10$FUQf220OgPr2hCryxfOZ2uMpU2mRpKGmdkKSTTIqpvB6X/dgFClCG','karaG',1,NULL,'0','0',NULL,NULL,'0','0',NULL,NULL,'2025-12-09 04:36:13.455403',NULL);
INSERT INTO `` (`id`,`email`,`first_name`,`last_name`,`password`,`username`,`enabled`,`account_expiry_date`,`account_non_expired`,`account_non_locked`,`create_date`,`credentials_expiry_date`,`credentials_non_expired`,`is_two_factor_enabled`,`sign_up_method`,`two_factor_secret`,`updated_date`,`role_id`) VALUES (33,'nwatkins@gmail.','Nyla','Watkins','$2a$10$xEiLKQDu7Ik1ZyxiEVvfyOCne/4ZqWaEpQUivwuZR7SOUX40rPO16','NighLuh',1,NULL,'0','0',NULL,NULL,'0','0',NULL,NULL,'2025-12-09 04:36:13.518325',NULL);
INSERT INTO `` (`id`,`email`,`first_name`,`last_name`,`password`,`username`,`enabled`,`account_expiry_date`,`account_non_expired`,`account_non_locked`,`create_date`,`credentials_expiry_date`,`credentials_non_expired`,`is_two_factor_enabled`,`sign_up_method`,`two_factor_secret`,`updated_date`,`role_id`) VALUES (44,'user44@example.com','Unknown','Unknown','$2a$10$8O/J.a1NCTQ.9PLVI1Wyp.GKrdaoN4z7Un6exA1TM5jR1z.uVAHIi','user',1,NULL,'0','0',NULL,NULL,'0','0',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id`,`email`,`first_name`,`last_name`,`password`,`username`,`enabled`,`account_expiry_date`,`account_non_expired`,`account_non_locked`,`create_date`,`credentials_expiry_date`,`credentials_non_expired`,`is_two_factor_enabled`,`sign_up_method`,`two_factor_secret`,`updated_date`,`role_id`) VALUES (45,'user45@example.com','Unknown','Unknown','$2a$10$mXMlbY.8lQAc.QUmOsvxbu/31sJvNCKMlmuPkILCZks3ZkDC4pT7a','admin',1,NULL,'0','0',NULL,NULL,'0','0',NULL,NULL,NULL,NULL);
INSERT INTO `` (`id`,`email`,`first_name`,`last_name`,`password`,`username`,`enabled`,`account_expiry_date`,`account_non_expired`,`account_non_locked`,`create_date`,`credentials_expiry_date`,`credentials_non_expired`,`is_two_factor_enabled`,`sign_up_method`,`two_factor_secret`,`updated_date`,`role_id`) VALUES (46,'user1@example.com','User','One','$2a$10$I.N8GC7fDx/1vzvG7cjQcOF2vG2CslehrCIQQoSN.yvjUm9j.fJC6','user1',1,'2026-12-03','1','0','2025-12-04 01:41:51.852523','2026-12-03','1','0',NULL,NULL,'2025-12-04 01:41:51.852589',1);
INSERT INTO `` (`id`,`email`,`first_name`,`last_name`,`password`,`username`,`enabled`,`account_expiry_date`,`account_non_expired`,`account_non_locked`,`create_date`,`credentials_expiry_date`,`credentials_non_expired`,`is_two_factor_enabled`,`sign_up_method`,`two_factor_secret`,`updated_date`,`role_id`) VALUES (47,'admin1@example.com','Admin','One','$2a$10$34VgeiDWYK7DSuTY6m0a6OU5V89KD2.2ujS0thVuwx98tut6RN5KG','admin1',1,'2026-12-03','1','1','2025-12-04 01:41:51.937909','2026-12-03','1','0',NULL,NULL,'2025-12-04 01:41:51.937927',2);
